version: '3.8'
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3500:3500
    depends_on:
      - mongodb
  client:
    build:
      context: ./client/client
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  mongodb:
    image: mongo:latest
    volumes:
      - ./../mydata:/data/db
    ports:
      - "27017:27017"
volumes:
  mydata:
# how to build an image
# docker build -t backend .